micronaut:
  application:
    name: MLTechnical
  router:
    static-resources:
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /swagger/rapidoc/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: NONE
    dialect: H2
    formatSql: true
  # Test only
#  mysql:
#    url: jdbc:mysql://localhost:3306/${dbname:ml}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&useTimezone=true&serverTimezone=UTC
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#    schema-generate: NONE
#    dialect: MYSQL

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    properties:
      hibernate:
        show_sql: false # prints SQL
        format_sql: true
        id:
          new_generator_mappings: false
        hbm2ddl:
          auto: none

# Liquibase
liquibase:
  enabled: true
  datasources:
    default:
      change-log: classpath:migrations/changelog.json
    mysql:
      enabled: false
      change-log: classpath:migrations/changelog.json
